/*
 * stepper.h  —  NEMA 17 Stepper Motor Control (potentiometer input)
 * Board  : STM32 Nucleo-F767ZI  (Vehicle Base — merged firmware)
 * Motor  : 17HE15-1504S  (1.8°/step, 1.5 A/phase, bipolar)
 * Driver : Opto-isolated microstep driver (TB6600/DM542 style)
 *
 * Hardware wiring:
 *   PB4  (TIM3_CH1, AF2) → PUL+   step pulse output (50% duty PWM)
 *   PC8  (GPIO_OUTPUT)   → DIR+   direction
 *   ENA+                 → 3.3 V  (motor permanently energised / holds position)
 *   PUL-, DIR-, ENA-     → GND
 *
 * Potentiometer inputs (each wired as a voltage divider 3.3V–pot–GND):
 *   PC0  (ADC1_IN10)  →  wiper of CW pot   (drives clockwise rotation)
 *   PA3  (ADC1_IN3)   →  wiper of CCW pot  (drives counter-clockwise rotation)
 *
 * Control law (dual-pot throttle scheme):
 *   Both pots at rest (≤STEPPER_DEADBAND)        → motor stopped
 *   Only CW  pot active (>STEPPER_DEADBAND)      → CW  rotation, speed ∝ deflection
 *   Only CCW pot active (>STEPPER_DEADBAND)      → CCW rotation, speed ∝ deflection
 *   Both pots active                             → safety stop (conflict)
 *   Soft ramp limits acceleration to prevent missed steps
 *   Direction reversal always ramps through zero first
 *
 * Timer configuration (generated by CubeIDE from .ioc):
 *   TIM3 prescaler = 95  → tick = 1 µs  (96 MHz APB1×2 / 96)
 *   ARR updated at runtime: ARR = (1 000 000 / step_freq_Hz) − 1
 *   CCR1 = ARR / 2  (50 % duty — clean rising edge for step input)
 *   Auto-reload preload enabled → glitch-free frequency transitions
 *
 * ADC configuration (generated by CubeIDE from .ioc, with USER CODE overrides
 * in main.c MX_ADC1_Init to remap rank 2 from IN13 → IN3 and to put PA3
 * back into analog mode after the unused USART2 grabs it):
 *   ADC1, IN10 + IN3, scan + continuous, 480-cycle sampling
 *   DMA2 Stream 0, circular, half-word → uint16_t adc_dma_buf[2]
 */

#ifndef STEPPER_H
#define STEPPER_H

#include "stm32f7xx_hal.h"

/* ── Tuning constants ──────────────────────────────────────────────────────
 * Adjust these to match your physical setup once the motor is running.     */

/** Rest-zone threshold (ADC counts, 12-bit: 0…4095).
 *  Each pot rests near 0; samples ≤ this value are treated as "no command".
 *  Increase if motor creeps when pot is released; decrease for finer start. */
#define STEPPER_DEADBAND     150u

/** Minimum step frequency (Hz) once pot leaves the dead zone.
 *  Prevents very slow, jerky motion.  Lower = finer low-speed control. */
#define STEPPER_FREQ_MIN     200u

/** Maximum step frequency (Hz) at full pot deflection.
 *  At 1/8 microstepping (1600 steps/rev): 5000 Hz ≈ 188 RPM.
 *  Reduce if motor stalls under load. */
#define STEPPER_FREQ_MAX     5000u

/** Acceleration ramp step (Hz added/removed per STEPPER_Update() call).
 *  Called every ~1 ms → 100 Hz/ms = 100 000 steps/s² acceleration.
 *  Increase for snappier response; decrease if motor loses steps on ramps. */
#define STEPPER_RAMP_STEP    100u

/* ── GPIO ─────────────────────────────────────────────────────────────────*/
#define STEP_DIR_PORT   GPIOC
#define STEP_DIR_PIN    GPIO_PIN_8   /* PC8 → DIR+ on driver */

/* ── Status snapshot (for UI / diagnostics) ────────────────────────────── */
typedef struct {
    int32_t  current_freq;   /* Signed Hz.  >0 = CW, <0 = CCW, 0 = stopped */
    int32_t  target_freq;    /* Signed Hz.  Latest commanded target         */
    uint16_t cw_adc;         /* Last CW-pot  sample (ADC1_IN10 / PC0)       */
    uint16_t ccw_adc;        /* Last CCW-pot sample (ADC1_IN13 / PC3)       */
    uint8_t  running;        /* 1 when TIM3 CH1 PWM output is enabled       */
} STEPPER_Status_t;

/* ── Public API ────────────────────────────────────────────────────────────*/

/**
 * STEPPER_Init — one-time setup called from main USER CODE BEGIN 2.
 *
 * Assumes CubeIDE has already generated:
 *   MX_TIM3_Init()  — TIM3 CH1 PWM, prescaler 95, ARPE enabled
 *   MX_ADC1_Init()  — ADC1 IN10/IN13 scan, continuous, DMA circular
 *   MX_DMA_Init()   — DMA2 Stream0
 * and PC8 is configured as GPIO_OUTPUT by MX_GPIO_Init().
 *
 * Starts ADC DMA so adc_dma_buf[] stays live without CPU polling.
 * Motor is NOT pulsed until STEPPER_Update() raises a non-zero target.
 */
void STEPPER_Init(void);

/**
 * STEPPER_Update — call every main-loop iteration (~1 ms) with the two
 * latest ADC samples (CW-pot first, CCW-pot second).
 *
 * @param cw_adc   12-bit ADC sample from the CW-throttle pot  [0, 4095]
 * @param ccw_adc  12-bit ADC sample from the CCW-throttle pot [0, 4095]
 *
 * Internally:
 *   1. Picks target frequency from whichever pot is above STEPPER_DEADBAND.
 *      Both-at-rest or both-active → target 0 (safe stop).
 *   2. Forces target through 0 when direction reversal is required.
 *   3. Ramps s_current_freq toward target by at most STEPPER_RAMP_STEP.
 *   4. Updates TIM3 ARR/CCR1 and starts/stops PWM output accordingly.
 */
void STEPPER_Update(uint16_t cw_adc, uint16_t ccw_adc);

/**
 * STEPPER_Stop — immediately halt step pulses and reset internal state.
 * Call on watchdog timeout, fault condition, or emergency stop.
 */
void STEPPER_Stop(void);

/**
 * STEPPER_GetStatus — copy the current stepper state into *out for UI /
 * diagnostic use.  Safe to call from the main loop (no blocking I/O).
 */
void STEPPER_GetStatus(STEPPER_Status_t *out);

/**
 * STEPPER_SetTargetFreq — push a signed step frequency target directly,
 * bypassing the dual-pot input path. Intended for the Arm STM32 where the
 * target comes from a joystick frame on UART instead of two ADC pots.
 *
 *   hz > 0  → CW  rotation (DIR pin HIGH)
 *   hz < 0  → CCW rotation (DIR pin LOW)
 *   hz = 0  → ramp to stop
 *
 * Clamped to ±STEPPER_FREQ_MAX. Pair with STEPPER_Tick() in the main loop;
 * STEPPER_Update() will overwrite the target (using zero pots as input) and
 * is not the right call once you've moved to the joystick path.
 */
void STEPPER_SetTargetFreq(int32_t hz);

/**
 * STEPPER_Tick — run the ramp + reversal-through-zero logic and push the
 * new frequency to TIM3 + DIR pin. Intended to be called every ~1 ms from
 * the main loop on the Arm STM32 where the target is set via
 * STEPPER_SetTargetFreq() rather than computed from ADC pots.
 *
 * Equivalent to the back half of STEPPER_Update() with the pot-evaluation
 * skipped, so it leaves s_target_freq alone.
 */
void STEPPER_Tick(void);

#endif /* STEPPER_H */
