/*
 * lcd.h  —  16x2 HD44780 LCD over I2C (PCF8574 backpack)
 * Board : STM32 Nucleo-F767ZI  (Vehicle Base)
 *
 * Wiring (breadboard):
 *   STM32 PB8 (I2C1 SCL) → LCD module SCL
 *   STM32 PB9 (I2C1 SDA) → LCD module SDA
 *   LCD VCC → 5 V,  LCD GND → GND
 *
 * PCF8574 I2C address:
 *   Most modules ship as 0x27.  If the display stays blank, try 0x3F.
 *   Change LCD_I2C_ADDR below if needed.
 *
 * PCF8574 pin-to-HD44780 mapping used by this driver:
 *   P0 = RS,  P1 = RW,  P2 = EN,  P3 = Backlight
 *   P4 = D4,  P5 = D5,  P6 = D6,  P7 = D7
 */

#ifndef LCD_H
#define LCD_H

#include "stm32f7xx_hal.h"
#include <stdint.h>

/* I2C handle — generated by CubeMX when I2C1 is enabled */
extern I2C_HandleTypeDef hi2c1;
#define LCD_I2C         hi2c1

/* 7-bit I2C address of the PCF8574 expander */
#define LCD_I2C_ADDR    0x27    /* Change to 0x3F if display is blank */

/* ---- Public API -------------------------------------------------------- */
void LCD_Init       (void);
void LCD_Clear      (void);
void LCD_SetCursor  (uint8_t row, uint8_t col);   /* row 0/1, col 0-15    */
void LCD_Print      (const char *str);
void LCD_WriteStatus(const char *line1, const char *line2); /* Both lines */

#endif /* LCD_H */
